module.exports={
    module:{
        rules:[{
            test:/\.m?(js|tsx|ts)$/,
            exclude:/node_modules/,
            use:{
                loader:'babel-loader',
                options:{
                    presets:['@babel/preset-react','@babel/preset-env'],
                    plugins:['@babel/plugin-transform-runtime']
                }
            }
        }]
    }
}